// SPDX-FileCopyrightText: 2021-2026 RizinOrg <info@rizin.re>
// SPDX-License-Identifier: LGPL-3.0-only
//
// WARNING: This file was auto-generated by cmd_descs_generate.py script. Do not
// modify it manually. Look at cmd_descs.yaml if you want to update commands.
//

#include <cmd_descs.h>

static const RzCmdDescDetail cmd_fridas_details[2];
static const RzCmdDescDetail cmd_fridau_details[3];
static const RzCmdDescDetail cmd_fridad_details[2];
static const RzCmdDescDetail cmd_frida_details[4];
static const RzCmdDescArg cmd_fridau_args[2];

static const RzCmdDescDetailEntry cmd_frida_Session_space_status_detail_entries[] = {
	{ .text = "fridas", .arg_str = NULL, .comment = "Print plugin/session status in plain text" },
	{ .text = "fridasj", .arg_str = NULL, .comment = "Print plugin/session status as JSON" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_URI_space_grammar_detail_entries[] = {
	{ .text = "fridau ", .arg_str = "frida://attach/local//1234", .comment = "Validate URI for attaching to local PID 1234" },
	{ .text = "fridau ", .arg_str = "frida://spawn/usb/device-1/com.example.app", .comment = "Validate URI for spawning an Android package over USB" },
	{ .text = "fridau ", .arg_str = "frida://attach/remote/127.0.0.1:27042/4321", .comment = "Validate URI for attaching to PID 4321 over remote frida-server" },
	{ .text = "fridauj ", .arg_str = "frida://launch/local///bin/ls", .comment = "Validate launch URI for /bin/ls and emit JSON" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_Device_space_enumeration_detail_entries[] = {
	{ .text = "fridadj", .arg_str = NULL, .comment = "Enumerate connected Frida devices as JSON" },
	{ 0 },
};
static const RzCmdDescDetail cmd_frida_details[] = {
	{ .name = "Session status", .entries = cmd_frida_Session_space_status_detail_entries },
	{ .name = "URI grammar", .entries = cmd_frida_URI_space_grammar_detail_entries },
	{ .name = "Device enumeration", .entries = cmd_frida_Device_space_enumeration_detail_entries },
	{ 0 },
};
static const RzCmdDescHelp cmd_frida_help = {
	.summary = "Interact with Frida targets",
	.description = "Commands for the rz-frida integration covering plugin and session status, frida:// URI validation, and Frida device enumeration.",
	.details = cmd_frida_details,
};
static const RzCmdDescDetailEntry cmd_fridas_Examples_detail_entries[] = {
	{ .text = "fridas", .arg_str = NULL, .comment = "active and state lines in plain text" },
	{ .text = "fridasj", .arg_str = NULL, .comment = "Same data wrapped in the rz-frida JSON envelope" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridas_details[] = {
	{ .name = "Examples", .entries = cmd_fridas_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridas_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridas_help = {
	.summary = "Print Frida session status",
	.description = "Reports whether a session is active and prints the current session state (new, resolved, connecting, attached, detaching, closed, or error).",
	.details = cmd_fridas_details,
	.args = cmd_fridas_args,
};

static const RzCmdDescDetailEntry cmd_fridau_URI_space_grammar_detail_entries[] = {
	{ .text = "frida://", .arg_str = "<action>/<transport>/<device>/<target>", .comment = "Full grammar for the frida:// URI" },
	{ .text = "action   ", .arg_str = "= list | apps | attach | spawn | launch", .comment = "Operation requested for the session" },
	{ .text = "transport", .arg_str = "= local | usb | remote", .comment = "Transport used to reach the Frida target" },
	{ .text = "device   ", .arg_str = "= empty | device-id | host:port", .comment = "Empty for local, id for USB, host:port for remote" },
	{ .text = "target   ", .arg_str = "= pid | process-name | package-name | executable-path", .comment = "Target selector required by attach/spawn/launch" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_fridau_Examples_detail_entries[] = {
	{ .text = "fridau ", .arg_str = "frida://attach/local//1234", .comment = "Attach to local PID 1234" },
	{ .text = "fridau ", .arg_str = "frida://spawn/usb/device-1/com.example.app", .comment = "Spawn an Android package on a USB device" },
	{ .text = "fridau ", .arg_str = "frida://launch/local///bin/ls", .comment = "Launch /bin/ls locally (note the leading slash in the path)" },
	{ .text = "fridauj ", .arg_str = "frida://attach/remote/127.0.0.1:27042/4321", .comment = "Validate remote-attach URI and emit JSON" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridau_details[] = {
	{ .name = "URI grammar", .entries = cmd_fridau_URI_space_grammar_detail_entries },
	{ .name = "Examples", .entries = cmd_fridau_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridau_args[] = {
	{
		.name = "uri",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridau_help = {
	.summary = "Validate a frida:// URI",
	.description = "Parses and validates a frida:// URI without contacting any Frida device. Useful for verifying URI syntax in scripts or CI before attempting to attach.",
	.details = cmd_fridau_details,
	.args = cmd_fridau_args,
};

static const RzCmdDescDetailEntry cmd_fridad_Examples_detail_entries[] = {
	{ .text = "fridadj", .arg_str = NULL, .comment = "List devices as JSON; returns a frida_unavailable error if built without frida-core" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridad_details[] = {
	{ .name = "Examples", .entries = cmd_fridad_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridad_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridad_help = {
	.summary = "List Frida devices",
	.description = "Enumerates devices known to the Frida device manager (local, USB, and remote) and emits a structured JSON reply.",
	.details = cmd_fridad_details,
	.args = cmd_fridad_args,
};

RZ_IPI void rzshell_cmddescs_init(RzCore *core) {
	RzCmdDesc *root_cd = rz_cmd_get_root(core->rcmd);
	rz_cmd_batch_start(core->rcmd);

	RzCmdDesc *cmd_frida_cd = rz_cmd_desc_group_new(core->rcmd, root_cd, "frida", NULL, NULL, &cmd_frida_help);
	rz_warn_if_fail(cmd_frida_cd);
	RzCmdDesc *cmd_fridas_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridas", RZ_OUTPUT_MODE_STANDARD | RZ_OUTPUT_MODE_JSON, rz_cmd_fridas_handler, &cmd_fridas_help);
	rz_warn_if_fail(cmd_fridas_cd);

	RzCmdDesc *cmd_fridau_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridau", RZ_OUTPUT_MODE_STANDARD | RZ_OUTPUT_MODE_JSON, rz_cmd_fridau_handler, &cmd_fridau_help);
	rz_warn_if_fail(cmd_fridau_cd);

	RzCmdDesc *cmd_fridad_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridad", RZ_OUTPUT_MODE_JSON, rz_cmd_fridad_handler, &cmd_fridad_help);
	rz_warn_if_fail(cmd_fridad_cd);
	rz_cmd_batch_end(core->rcmd);
}
