// SPDX-FileCopyrightText: 2021-2026 RizinOrg <info@rizin.re>
// SPDX-License-Identifier: LGPL-3.0-only
//
// WARNING: This file was auto-generated by cmd_descs_generate.py script. Do not
// modify it manually. Look at cmd_descs.yaml if you want to update commands.
//

#include <cmd_descs.h>

static const RzCmdDescDetail cmd_fridas_details[2];
static const RzCmdDescDetail cmd_fridau_details[3];
static const RzCmdDescDetail cmd_fridad_details[2];
static const RzCmdDescDetail cmd_fridap_details[2];
static const RzCmdDescDetail cmd_fridaa_details[2];
static const RzCmdDescDetail cmd_fridao_details[2];
static const RzCmdDescDetail cmd_fridar_details[2];
static const RzCmdDescDetail cmd_fridac_details[2];
static const RzCmdDescDetail cmd_fridae_details[2];
static const RzCmdDescDetail cmd_fridal_details[2];
static const RzCmdDescDetail cmd_fridai_details[2];
static const RzCmdDescDetail cmd_frida_details[8];
static const RzCmdDescArg cmd_fridau_args[2];
static const RzCmdDescArg cmd_fridap_args[2];
static const RzCmdDescArg cmd_fridaa_args[2];
static const RzCmdDescArg cmd_fridao_args[2];
static const RzCmdDescArg cmd_fridae_args[2];
static const RzCmdDescArg cmd_fridal_args[2];

static const RzCmdDescDetailEntry cmd_frida_Session_space_status_detail_entries[] = {
	{ .text = "fridas", .arg_str = NULL, .comment = "Print plugin/session status in plain text" },
	{ .text = "fridasj", .arg_str = NULL, .comment = "Print plugin/session status as JSON" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_URI_space_grammar_detail_entries[] = {
	{ .text = "fridau ", .arg_str = "frida://attach/local//1234", .comment = "Validate URI for attaching to local PID 1234" },
	{ .text = "fridau ", .arg_str = "frida://spawn/usb/device-1/com.example.app", .comment = "Validate URI for spawning an Android package over USB" },
	{ .text = "fridau ", .arg_str = "frida://attach/remote/127.0.0.1:27042/4321", .comment = "Validate URI for attaching to PID 4321 over remote frida-server" },
	{ .text = "fridauj ", .arg_str = "frida://launch/local///bin/ls", .comment = "Validate launch URI for /bin/ls and emit JSON" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_Device_space_enumeration_detail_entries[] = {
	{ .text = "fridadj", .arg_str = NULL, .comment = "Enumerate connected Frida devices as JSON" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_Process_space_listing_detail_entries[] = {
	{ .text = "fridapj", .arg_str = NULL, .comment = "Enumerate local processes as JSON" },
	{ .text = "fridapj ", .arg_str = "frida://list/usb/device-1/", .comment = "Enumerate processes on a USB device as JSON" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_Application_space_listing_detail_entries[] = {
	{ .text = "fridaaj", .arg_str = NULL, .comment = "Enumerate local applications as JSON" },
	{ .text = "fridaaj ", .arg_str = "frida://apps/usb/device-1/", .comment = "Enumerate applications on a USB device as JSON" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_Session_space_control_detail_entries[] = {
	{ .text = "fridaoj ", .arg_str = "frida://spawn/local///bin/ls", .comment = "Spawn /bin/ls suspended and open a session" },
	{ .text = "fridarj", .arg_str = NULL, .comment = "Resume the spawned target" },
	{ .text = "fridacj", .arg_str = NULL, .comment = "Close the open session" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_frida_Script_space_execution_detail_entries[] = {
	{ .text = "fridaij", .arg_str = NULL, .comment = "Ping the agent and read its version and target info" },
	{ .text = "fridaej ", .arg_str = "Process.arch", .comment = "Evaluate a JavaScript expression in the target" },
	{ .text = "fridalj ", .arg_str = "hook.js", .comment = "Load and evaluate a JavaScript file in the target" },
	{ 0 },
};
static const RzCmdDescDetail cmd_frida_details[] = {
	{ .name = "Session status", .entries = cmd_frida_Session_space_status_detail_entries },
	{ .name = "URI grammar", .entries = cmd_frida_URI_space_grammar_detail_entries },
	{ .name = "Device enumeration", .entries = cmd_frida_Device_space_enumeration_detail_entries },
	{ .name = "Process listing", .entries = cmd_frida_Process_space_listing_detail_entries },
	{ .name = "Application listing", .entries = cmd_frida_Application_space_listing_detail_entries },
	{ .name = "Session control", .entries = cmd_frida_Session_space_control_detail_entries },
	{ .name = "Script execution", .entries = cmd_frida_Script_space_execution_detail_entries },
	{ 0 },
};
static const RzCmdDescHelp cmd_frida_help = {
	.summary = "Interact with Frida targets",
	.description = "Commands for the rz-frida integration covering plugin and session status, frida:// URI validation, device, process, and application enumeration, and session lifecycle across local, USB, and remote targets.",
	.details = cmd_frida_details,
};
static const RzCmdDescDetailEntry cmd_fridas_Examples_detail_entries[] = {
	{ .text = "fridas", .arg_str = NULL, .comment = "active and state lines in plain text" },
	{ .text = "fridasj", .arg_str = NULL, .comment = "Same data wrapped in the rz-frida JSON envelope" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridas_details[] = {
	{ .name = "Examples", .entries = cmd_fridas_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridas_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridas_help = {
	.summary = "Print Frida session status",
	.description = "Reports whether a session is active and prints the current session state (new, resolved, connecting, attached, detaching, closed, or error).",
	.details = cmd_fridas_details,
	.args = cmd_fridas_args,
};

static const RzCmdDescDetailEntry cmd_fridau_URI_space_grammar_detail_entries[] = {
	{ .text = "frida://", .arg_str = "<action>/<transport>/<device>/<target>", .comment = "Full grammar for the frida:// URI" },
	{ .text = "action   ", .arg_str = "= list | apps | attach | spawn | launch", .comment = "Operation requested for the session" },
	{ .text = "transport", .arg_str = "= local | usb | remote", .comment = "Transport used to reach the Frida target" },
	{ .text = "device   ", .arg_str = "= empty | device-id | host:port", .comment = "Empty for local, id for USB, host:port for remote" },
	{ .text = "target   ", .arg_str = "= pid | process-name | package-name | executable-path", .comment = "Target selector required by attach/spawn/launch" },
	{ 0 },
};

static const RzCmdDescDetailEntry cmd_fridau_Examples_detail_entries[] = {
	{ .text = "fridau ", .arg_str = "frida://attach/local//1234", .comment = "Attach to local PID 1234" },
	{ .text = "fridau ", .arg_str = "frida://spawn/usb/device-1/com.example.app", .comment = "Spawn an Android package on a USB device" },
	{ .text = "fridau ", .arg_str = "frida://launch/local///bin/ls", .comment = "Launch /bin/ls locally (note the leading slash in the path)" },
	{ .text = "fridauj ", .arg_str = "frida://attach/remote/127.0.0.1:27042/4321", .comment = "Validate remote-attach URI and emit JSON" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridau_details[] = {
	{ .name = "URI grammar", .entries = cmd_fridau_URI_space_grammar_detail_entries },
	{ .name = "Examples", .entries = cmd_fridau_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridau_args[] = {
	{
		.name = "uri",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridau_help = {
	.summary = "Validate a frida:// URI",
	.description = "Parses and validates a frida:// URI without contacting any Frida device. Useful for verifying URI syntax in scripts or CI before attempting to attach.",
	.details = cmd_fridau_details,
	.args = cmd_fridau_args,
};

static const RzCmdDescDetailEntry cmd_fridad_Examples_detail_entries[] = {
	{ .text = "fridadj", .arg_str = NULL, .comment = "List devices as JSON; returns a frida_unavailable error if built without frida-core" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridad_details[] = {
	{ .name = "Examples", .entries = cmd_fridad_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridad_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridad_help = {
	.summary = "List Frida devices",
	.description = "Enumerates devices known to the Frida device manager (local, USB, and remote) and emits a structured JSON reply.",
	.details = cmd_fridad_details,
	.args = cmd_fridad_args,
};

static const RzCmdDescDetailEntry cmd_fridap_Examples_detail_entries[] = {
	{ .text = "fridapj", .arg_str = NULL, .comment = "List local processes as JSON, returns a frida_unavailable error if built without frida-core" },
	{ .text = "fridapj ", .arg_str = "frida://list/usb/device-1/", .comment = "List processes on a USB device by id" },
	{ .text = "fridapj ", .arg_str = "frida://list/remote/127.0.0.1:27042/", .comment = "List processes on a remote frida-server" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridap_details[] = {
	{ .name = "Examples", .entries = cmd_fridap_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridap_args[] = {
	{
		.name = "uri",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,
		.optional = true,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridap_help = {
	.summary = "List processes on a device",
	.description = "Enumerates the processes visible to a Frida device and emits a structured JSON reply. With no argument it lists the local device, or pass a frida:// URI to select a USB or remote device.",
	.details = cmd_fridap_details,
	.args = cmd_fridap_args,
};

static const RzCmdDescDetailEntry cmd_fridaa_Examples_detail_entries[] = {
	{ .text = "fridaaj", .arg_str = NULL, .comment = "List local applications as JSON, returns a frida_unavailable error if built without frida-core" },
	{ .text = "fridaaj ", .arg_str = "frida://apps/usb/device-1/", .comment = "List applications on a USB device by id" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridaa_details[] = {
	{ .name = "Examples", .entries = cmd_fridaa_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridaa_args[] = {
	{
		.name = "uri",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,
		.optional = true,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridaa_help = {
	.summary = "List applications on a device",
	.description = "Enumerates the applications known to a Frida device and emits a structured JSON reply. With no argument it lists the local device, or pass a frida:// URI to select a USB or remote device. Application listing is most useful for Android and iOS targets reached over USB.",
	.details = cmd_fridaa_details,
	.args = cmd_fridaa_args,
};

static const RzCmdDescDetailEntry cmd_fridao_Examples_detail_entries[] = {
	{ .text = "fridaoj ", .arg_str = "frida://attach/local//1234", .comment = "Attach to local PID 1234" },
	{ .text = "fridaoj ", .arg_str = "frida://attach/usb//com.example.app", .comment = "Attach by process name on the single USB device" },
	{ .text = "fridaoj ", .arg_str = "frida://spawn/usb//com.example.app", .comment = "Spawn an Android package suspended over USB, resume with fridarj" },
	{ .text = "fridaoj ", .arg_str = "frida://launch/local///bin/ls", .comment = "Launch /bin/ls and resume it immediately" },
	{ .text = "fridaoj ", .arg_str = "frida://attach/remote/127.0.0.1:27042/1234", .comment = "Attach to PID 1234 over a remote frida-server" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridao_details[] = {
	{ .name = "Examples", .entries = cmd_fridao_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridao_args[] = {
	{
		.name = "uri",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridao_help = {
	.summary = "Open a Frida session",
	.description = "Opens a session for a frida:// URI on a local, USB, or remote device: attach to a pid or process name, spawn a target suspended, or launch and resume it. Stores the live session and emits a structured JSON reply.",
	.details = cmd_fridao_details,
	.args = cmd_fridao_args,
};

static const RzCmdDescDetailEntry cmd_fridar_Examples_detail_entries[] = {
	{ .text = "fridarj", .arg_str = NULL, .comment = "Resume the spawned target, and returns an error if no session is open" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridar_details[] = {
	{ .name = "Examples", .entries = cmd_fridar_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridar_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridar_help = {
	.summary = "Resume the open Frida session",
	.description = "Resumes a target that was spawned suspended by the open command. Emits a structured JSON reply.",
	.details = cmd_fridar_details,
	.args = cmd_fridar_args,
};

static const RzCmdDescDetailEntry cmd_fridac_Examples_detail_entries[] = {
	{ .text = "fridacj", .arg_str = NULL, .comment = "Close the open session and return an error if none is open" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridac_details[] = {
	{ .name = "Examples", .entries = cmd_fridac_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridac_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridac_help = {
	.summary = "Close the open Frida session",
	.description = "Detaches the open session and forgets it. A target that was spawned but never resumed is killed. An attached or launched target keeps running. Emits a structured JSON reply.",
	.details = cmd_fridac_details,
	.args = cmd_fridac_args,
};

static const RzCmdDescDetailEntry cmd_fridae_Examples_detail_entries[] = {
	{ .text = "fridaej ", .arg_str = "Process.arch", .comment = "Read the target architecture from the agent" },
	{ .text = "fridaej ", .arg_str = "\"1 + 1\"", .comment = "Evaluate an expression, quote it when it has spaces" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridae_details[] = {
	{ .name = "Examples", .entries = cmd_fridae_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridae_args[] = {
	{
		.name = "source",
		.type = RZ_CMD_ARG_TYPE_STRING,
		.flags = RZ_CMD_ARG_FLAG_LAST,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridae_help = {
	.summary = "Evaluate JavaScript in the target",
	.description = "Loads the rz-frida agent into the open session on first use, then evaluates a JavaScript expression inside the target and returns its value and type. Quote the expression when it contains spaces, or use fridal for a script that lives in a file.",
	.details = cmd_fridae_details,
	.args = cmd_fridae_args,
};

static const RzCmdDescDetailEntry cmd_fridal_Examples_detail_entries[] = {
	{ .text = "fridalj ", .arg_str = "hook.js", .comment = "Evaluate the script in hook.js inside the target" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridal_details[] = {
	{ .name = "Examples", .entries = cmd_fridal_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridal_args[] = {
	{
		.name = "file",
		.type = RZ_CMD_ARG_TYPE_FILE,

	},
	{ 0 },
};
static const RzCmdDescHelp cmd_fridal_help = {
	.summary = "Load and evaluate a JavaScript file in the target",
	.description = "Reads a JavaScript file from disk and evaluates it inside the target through the rz-frida agent. Useful for instrumentation scripts that are too large to pass on the command line.",
	.details = cmd_fridal_details,
	.args = cmd_fridal_args,
};

static const RzCmdDescDetailEntry cmd_fridai_Examples_detail_entries[] = {
	{ .text = "fridaij", .arg_str = NULL, .comment = "Ping the agent and read its version and target info" },
	{ 0 },
};
static const RzCmdDescDetail cmd_fridai_details[] = {
	{ .name = "Examples", .entries = cmd_fridai_Examples_detail_entries },
	{ 0 },
};
static const RzCmdDescArg cmd_fridai_args[] = {
	{ 0 },
};
static const RzCmdDescHelp cmd_fridai_help = {
	.summary = "Ping the agent in the target",
	.description = "Loads the rz-frida agent into the open session on first use and pings it, returning the agent version and the target platform, architecture, and pointer size. A quick way to check the host-agent message channel is alive.",
	.details = cmd_fridai_details,
	.args = cmd_fridai_args,
};

RZ_IPI void rzshell_cmddescs_init(RzCore *core) {
	RzCmdDesc *root_cd = rz_cmd_get_root(core->rcmd);
	rz_cmd_batch_start(core->rcmd);

	RzCmdDesc *cmd_frida_cd = rz_cmd_desc_group_new(core->rcmd, root_cd, "frida", NULL, NULL, &cmd_frida_help);
	rz_warn_if_fail(cmd_frida_cd);
	RzCmdDesc *cmd_fridas_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridas", RZ_OUTPUT_MODE_STANDARD | RZ_OUTPUT_MODE_JSON, rz_cmd_fridas_handler, &cmd_fridas_help);
	rz_warn_if_fail(cmd_fridas_cd);

	RzCmdDesc *cmd_fridau_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridau", RZ_OUTPUT_MODE_STANDARD | RZ_OUTPUT_MODE_JSON, rz_cmd_fridau_handler, &cmd_fridau_help);
	rz_warn_if_fail(cmd_fridau_cd);

	RzCmdDesc *cmd_fridad_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridad", RZ_OUTPUT_MODE_JSON, rz_cmd_fridad_handler, &cmd_fridad_help);
	rz_warn_if_fail(cmd_fridad_cd);

	RzCmdDesc *cmd_fridap_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridap", RZ_OUTPUT_MODE_JSON, rz_cmd_fridap_handler, &cmd_fridap_help);
	rz_warn_if_fail(cmd_fridap_cd);

	RzCmdDesc *cmd_fridaa_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridaa", RZ_OUTPUT_MODE_JSON, rz_cmd_fridaa_handler, &cmd_fridaa_help);
	rz_warn_if_fail(cmd_fridaa_cd);

	RzCmdDesc *cmd_fridao_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridao", RZ_OUTPUT_MODE_JSON, rz_cmd_fridao_handler, &cmd_fridao_help);
	rz_warn_if_fail(cmd_fridao_cd);

	RzCmdDesc *cmd_fridar_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridar", RZ_OUTPUT_MODE_JSON, rz_cmd_fridar_handler, &cmd_fridar_help);
	rz_warn_if_fail(cmd_fridar_cd);

	RzCmdDesc *cmd_fridac_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridac", RZ_OUTPUT_MODE_JSON, rz_cmd_fridac_handler, &cmd_fridac_help);
	rz_warn_if_fail(cmd_fridac_cd);

	RzCmdDesc *cmd_fridae_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridae", RZ_OUTPUT_MODE_JSON, rz_cmd_fridae_handler, &cmd_fridae_help);
	rz_warn_if_fail(cmd_fridae_cd);

	RzCmdDesc *cmd_fridal_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridal", RZ_OUTPUT_MODE_JSON, rz_cmd_fridal_handler, &cmd_fridal_help);
	rz_warn_if_fail(cmd_fridal_cd);

	RzCmdDesc *cmd_fridai_cd = rz_cmd_desc_argv_state_new(core->rcmd, cmd_frida_cd, "fridai", RZ_OUTPUT_MODE_JSON, rz_cmd_fridai_handler, &cmd_fridai_help);
	rz_warn_if_fail(cmd_fridai_cd);
	rz_cmd_batch_end(core->rcmd);
}
