// SPDX-FileCopyrightText: 2021-2026 RizinOrg <info@rizin.re>
// SPDX-License-Identifier: LGPL-3.0-only
//
// WARNING: This file was auto-generated by cmd_descs_generate.py script. Do not
// modify it manually. Look at cmd_descs.yaml if you want to update commands.
//

#include <rz_cmd.h>
#include <rz_core.h>
#include <rz_util.h>

// Command handlers, manually defined somewhere else
// "fridas"
RZ_IPI RzCmdStatus rz_cmd_fridas_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridau"
RZ_IPI RzCmdStatus rz_cmd_fridau_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridad"
RZ_IPI RzCmdStatus rz_cmd_fridad_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridap"
RZ_IPI RzCmdStatus rz_cmd_fridap_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridaa"
RZ_IPI RzCmdStatus rz_cmd_fridaa_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridao"
RZ_IPI RzCmdStatus rz_cmd_fridao_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridar"
RZ_IPI RzCmdStatus rz_cmd_fridar_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridac"
RZ_IPI RzCmdStatus rz_cmd_fridac_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridae"
RZ_IPI RzCmdStatus rz_cmd_fridae_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridal"
RZ_IPI RzCmdStatus rz_cmd_fridal_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);
// "fridai"
RZ_IPI RzCmdStatus rz_cmd_fridai_handler(RzCore *core, int argc, const char **argv, RzCmdStateOutput *state);

// Main function that initialize the entire commands tree
RZ_IPI void rzshell_cmddescs_init(RzCore *core);
